<?php
$moduledata = array(

    // This will be used on the menu and as the modules directory name.
    'modulename' => 'Calendar',

    // Who wrote this module. Can be a single name or an array of names.
    'author' => 'Nathan Weiler',

    // Email address for the author(s). Can be a single email address or an array of addresses.
    // If an array, order must match the author array or email will be sent to the wrong person.
    'authoremail' => 'ncweiler2@hotmail.com',

    // The language pack for this module.
    'Lang' => array(
        'en' => array(
            '15minutes' => '15 Minutes',
            '30minutes' => '30 Minutes',
            '45minutes' => '45 Minutes',
            '1hour' => '1 Hour',
            '2hours' => '2 Hours',
            '3hours' => '3 Hours',
            '4hours' => '4 Hours',
            'add' => 'Add',
            'addanotherdate' => 'Add another date',
            'addevent' => 'Add Event',
            'AddNewLocation' => 'Add New Location',
            'AddNewLocationBusinessMissingInfo' => 'You must provide an Email Address, Office Phone or Fax Number to save this contact.',
            'AddNewLocationBusinessMissingName' => 'Business name required to save contact info.',
            'AddNewLocationPersonalMissingInfo' => 'You must provide an Email Address, Work Phone or Cell Phone to save this contact.',
            'AddNewLocationPersonalMissingName' => 'You must provide a First Name or Last Name to save this contact.',
            'AddReminder' => 'Add reminder for this event',
            'AlarmDate' => 'Alarm Date:',
            'AlarmTime' => 'Alarm Time:',
            'AllDayEvent' => 'All Day Event',
            'AutomaticallyAddedForCalendarEvent' => 'Automatically added for calendar event',
            'BeforeEvent' => 'before event',
            'BetweenStartEndDates' => 'Between Start and End dates',
            'cancel' => 'Cancel',
            'clicktextboxtoselectdate' => 'Click the textbox next to the button to select a date.',
            'ClickToRefresh' => 'Click to refresh',
            'clicktosetdate' => 'Click To Set Date',
            'clicktosettime' => 'Click To Set Time',
            'ContactType' => 'Contact Type',
            'datapassedvalidation' => 'Click the \'Add Event\' button below to add the event to the calendar.',
            'date' => 'Date',
            'dateslist' => 'Dates List',
            'datesremindersinvalid' => 'Dates and/or reminders not set',
            'dailyview' => 'Daily View',
            'DeleteEventDatesAndTimesFailed' => 'Unable to delete event dates and times',
            'DeleteEvent' => 'Delete Event',
            'description' => 'Description',
            'DoesNotRepeat' => 'Does not repeat',
            'editevent' => 'Edit Event',
            'EndDate' => 'End Date',
            'endtime' => 'End Time',
            'event' => 'Event',
            'eventdate' => 'Event Date',
            'EventDateDeletionFailed' => 'Unable to delete event dates for event with ID #',
            'EventIn1Hr' => 'Event In 1Hr',
            'EventIn5Hrs' => 'Event In 5Hrs',
            'EventInfoMissingDescription' => 'The info for this event was not found. You can update the info if you know it or delete the event and re-add it.',
            'EventInfoDeletionFailed' => 'Unable to delete event info for event with ID #',
            'EventInsertFailed' => 'Unable to save event info',
            'eventname' => 'Event Name',
            'eventnamemissing' => 'Event name Missing',
            'EventNext' => 'Next Event',
            'EventPast' => 'Past Event',
            'eventupdatefailed' => 'Unable to update event info',
            'Friday' => 'Friday',
            'goback' => 'Go back',
            'GoThere' => 'Go There',
            'GoToThisWeek' => 'Go To This Week',
            'GoToToday' => 'Go to Today',
            'HasEvents' => 'Has Events',
            'InvalidDate' => ' is an invalid date.',
            'invalideventid' => 'An invalid Event ID was given.',
            'invalidstartendtime' => 'Invalid start/end time found.',
            'location' => 'Location',
            'LocationDetails' => 'Location Details',
            'LoginToAddEvent' => 'You will need to login to schedule an event for this time slot',
            'MissingEventName' => 'Event name required',
            'Monday' => 'Monday',
            'Monthly' => 'Monthly',
            'MonthlyView' => 'Monthly View',
            'nodatesselected' => 'No dates selected.',
            'NoEndDate' => 'No End Date',
            'NoEvents' => 'No Events',
            'noreminders' => 'No reminders',
            'noneselected' => 'None selected',
            'NoteAppliesToAllDates' => 'Note: Start/End time applies to all dates selected.',
            'NothingForThisTimeSlot' => 'Nothing is scheduled for this time slot',
            'publicevent' => 'Public Event',
            'publiceventcheckboxnote' => 'Leave box unchecked to keep others from seeing this event',
            'reminder' => 'Reminder',
            'reminderdate' => 'Reminder Date',
            'reminderinsertfailed' => 'Unable to save reminder info.',
            'reminderrequiresstarttime' => 'You need to set a start time before you can add a reminder.',
            'remindertime' => 'Reminder Time',
            'reminderslist' => 'Reminders List',
            'remove' => 'Remove',
            'Repeats' => 'Repeats',
            'Saturday' => 'Saturday',
            'save' => 'Save',
            'savechanges' => 'Save Changes',
            'ScheduleConflict' => 'An event is already scheduled for the date and time(s) you selected.',
            'select' => 'Select',
            'SelectDatesFromGrid' => 'Select event date(s) using the calendar below.',
            'selectalocation' => 'Select A Location',
            'SelectedDate' => 'Selected Date: ',
            'setlocation' => 'Set location',
            'SkipFederalHolidays' => 'Skip federal holidays',
            'StartDate' => 'Start Date',
            'starttime' => 'Start Time',
            'Sunday' => 'Sunday',
            'Thursday' => 'Thursday',
            'time' => 'Time',
            'TimesEvery' => 'time(s) every',
            'TodayHasEvents' => 'Today, Has Events',
            'TodayNoEvents' => 'Today, No Events',
            'Tuesday' => 'Tuesday',
            'UnableToAddNewLocation' => 'Unable to add new location',
            'UnableToSaveEventDates' => 'Unable to save event date(s)',
            'UnableToSetReminders' => 'Unable to set a reminder',
            'unabletoloadeventinfo' => 'Unable to load event info',
            'UsingTodaysDate' => 'Using todays date instead.',
            'ViewEvent' => 'View Event',
            'Wednesday' => 'Wednesday',
            'WeeklyView' => 'Weekly View',
            'Weekly' => 'Weekly',
            'Yearly' => 'Yearly',
        )
    )
);
?>
