<?php
$moduledata = array(

    // This will be used on the menu and as the modules directory name.
    'modulename' => 'Song Lyrics',

    // Who wrote this module. Can be a single name or an array of names.
    'author' => 'Nathan Weiler',

    // Email address for the author(s). Can be a single email address or an array of addresses.
    // If an array, order must match the author array or email will be sent to the wrong person.
    'authoremail' => 'ncweiler2@hotmail.com',

    // The language pack for this module.
    'Lang' => array(
        'en' => array(
            'addartist' => 'Add An Artist',
            'addalbum' => 'Add An Album',
            'addsong' => 'Add A Song',
            'AlbumIDNotSet' => 'Album ID Not Set',
            'albumname' => 'Album Name',
            'alsodeletesongs' => 'Also delete songs',
            'alsodeletecoverart' => 'Also Delete Cover Art',
            'Assign' => 'Assign',
            'AssignToAlbum' => 'Assign to album',
            'artistbio' => 'Bio',
            'artistname' => 'Artist Name',
            'AlbumsInDB' => 'Albums in Database',
            'backcover' => 'Back Cover',
            'cancel' => 'Cancel',
            'category' => 'Category',
            'changealbumart' => 'Change album art',
            'changealbumname' => 'Change Album',
            'changeartistname' => 'Change Artist',
            'checkifunknown' => 'Check if unknown',
            'ClearBackCover' => 'Clear Back Cover',
            'ClearFrontCover' => 'Clear Front Cover',
            'clickbrowsetochange' => 'Click "Browse" to change cover art',
            'clicktoenable' => 'Click to enable',
            'clicktoselectdate' => 'Click To Select Date',
            'confirmcoverartdeletion' => 'Are you sure you want to delete this cover art?',
            'CoverArtWillBeDeleted' => 'Cover art associated with this artist will be deleted.',
            'CoverArtWillNotBeDeleted' => 'Cover art associated with this artist will not be deleted.',
            'CurrentName' => 'Current name',
            'delete' => 'Delete',
            'deletealbum' => 'Delete Album',
            'deleteartistinfo' => 'Delete Artist Info',
            'editalbuminfo' => 'Edit Album Info',
            'editartistinfo' => 'Edit Artist Info',
            'editdetails' => 'Edit details',
            'editlyrics' => 'Edit lyrics',
            'editsong' => 'Edit Song',
            'editsonginfo' => 'Edit Song Info',
            'filenamemultimatch' => 'Multiple files with this name were found: ',
            'filenotfoundonserver' => 'The following file was not found on the server: ',
            'frontcover' => 'Front Cover',
            'genre' => 'Genre',
            'genrelist' => 'Genre List',
            'goback' => 'Go back',
            'gotoartistinfo' => 'Go To Artist Info',
            'invalidalbumid' => 'Invalid Album ID',
            'invalidartistid' => 'Invalid Artist ID',
            'invalidgenre' => 'Invalid genre specified',
            'invalidgenreid' => 'Invalid genre ID',
            'invalidsongid' => 'Invalid Song ID',
            'lyrics' => 'Lyrics',
            'makeselectionbelow' => 'Make selection below',
            'missingalbumname' => 'Missing album name',
            'missingartistname' => 'Missing artist name',
            'missinggenrename' => 'Genre name required',
            'missinglyrics' => 'Missing lyrics',
            'missingnewalbumname' => 'Missing name of new album',
            'missingnewartistname' => 'Missing name of new artist',
            'missingsongname' => 'Missing song name',
            'multipleaalbumssamename' => 'Multiple albums named "~~name~~" where found',
            'multipleartistssamename' => 'Multiple artists named "~~name~~" where found',
            'NextAlbum' => 'Next Album',
            'NextArtist' => 'Next Artist',
            'nextsong' => 'Next Song',
            'NewAlbumName' => 'New Album',
            'newartistname' => 'New Artist',
            'newgenre' => 'New Genre',
            'NewName' => 'New name',
            'noalbumsfound' => 'No albums found',
            'NoCoverArt' => 'No Cover Art',
            'NoGenresFound' => 'No genres found in database.',
            'noinfoindbforfile' => 'No info in the database for the following file: ',
            'NoOrphanedAlbums' => 'No oprhaned albums found',
            'NoOrphanedSongs' => 'No oprhaned songs found',
            'NoSongsInDB' => 'There were no songs found in the database.',
            'notset' => 'Not set',
            'orphanedalbums' => 'Orphaned Albums',
            'orphanedsongs' => 'Orphaned Songs',
            'orselectexistingart' => 'Or select from some already uploaded album art',
            'PrevAlbum' => 'Previous Album',
            'PrevArtist' => 'Previous Artist',
            'prevsong' => 'Previous Song',
            'refreshgenrelist' => 'Refresh Genre List',
            'releasedate' => 'Release Date',
            'reloadalbumdata' => 'Reload Album Data',
            'ReloadArtistData' => 'Reload Artist Data',
            'RenameAlbum' => 'Rename Album',
            'RenameGenre' => 'Rename Genre',
            'returntoartistlist' => 'Return To Artist List',
            'ReturnToSong' => 'Return To Song',
            'runtime' => 'Run Time',
            'save' => 'Save',
            'savechanges' => 'Save Changes',
            'searchfor' => 'Search for',
            'searchform' => 'Search Form',
            'servernouploadpermission' => 'The webserver does not have permission to upload cover art.',
            'setmpdvolume' => 'Set mpd volume level.',
            'SongList' => 'Song List',
            'songname' => 'Song Name',
            'SongsInDB' => 'Songs in Database',
            'tracktimenote' => 'Minutes:Seconds',
            'tracknumber' => 'Track #',
            'tracktime' => 'Length',
            'UnableToCreateDirectory' => 'Unable to create directory',
            'UnableToDeleteAlbumArt' => 'Unable to delete the album art',
            'UnableToDeleteAlbumInfo' => 'Unable to delete info for the album',
            'UnableToDeleteAllAlbums' => 'Unable to delete all of the albums',
            'UnableToDeleteArtistInfo' => 'Unable to delete artist info',
            'UnableToDeleteAllSongs' => 'Unable to delete all of the songs',
            'unabletodeletesong' => 'Unable to delete the song info.',
            'UnableToDeleteGenre' => 'Unable to delete genre',
            'UnableToDeleteSongInfo' => 'Unable to delete song info',
            'UnableToEditArtistInfo' => 'Unable to edit artist info',
            'unabletosavenewalbuminfo' => 'Unable to save new album info.',
            'unabletosavenewartistinfo' => 'Unable to save new artist info.',
            'unabletosavesongdata' => 'Unable to save song data',
            'unknown' => 'Unknown',
            'uploadfrontcoverart' => 'Upload Front Cover Art',
            'uploadbackcoverart' => 'Upload Back Cover Art',
            'viewalbum' => 'View album',
            'volume' => 'Volume',
            'wikipediaarticle' => 'Wikipedia Article',
            'WillAlsoDeleteAlbumsSongs' => 'This will also delete all albums and songs for this artist.',
        )
    )
);
?>
